name: Discord Theme Class Updater
description: Automatically update class names in your Discord themes
branding:
  icon: file-plus
  color: blue

inputs:
  folder:
    description: Folder that has your theme files
    default: themes
  ext:
    description: File extension to target
    default: css
  diff:
    description: URL or relative path to a file containing an old & new pair of class names
    default: https://raw.githubusercontent.com/SyndiShanX/Update-Classes/main/Changes.txt

outputs:
  changed:
    description: If any files have changed
  totalChanges:
    description: The total number of classes that were replaced

runs:
  using: node20
  main: dist/index.js
