name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Build forked version
        run: npm run build

      - name: Download non-forked version
        run: |
          mkdir -p old_version
          curl -L https://raw.githubusercontent.com/Metro420yt/class-update/refs/heads/master/dist/index.js -o old_version/index.js

      - name: Create test data (Light Version)
        run: |
          mkdir -p test_files
          for j in {1..1000}; do
            CLASS_NUM=$(( (j % 100) + 1 ))
            echo ".old-class-$CLASS_NUM { color: blue; border: 1px solid red; }" >> test_files/theme-large.css
          done

          for i in {1..100}; do
            echo "old-class-$i" >> stress_diff.txt
            echo "new-class-$i" >> stress_diff.txt
          done

      - name: Install Hyperfine
        run: sudo apt-get install -y hyperfine

      - name: Run Benchmark
        run: |
          hyperfine --warmup 2 \
            "INPUT_FOLDER=test_files INPUT_DIFF=stress_diff.txt INPUT_EXT=css node dist/index.js" \
            "INPUT_FOLDER=test_files INPUT_DIFF=stress_diff.txt INPUT_EXT=css node old_version/index.js"
